Switch build system from Maven to Gradle
komoot/photon pull request #789
Opened 2024-04-09 16:00 UTC by lonvia

I hope that Gradle offers a bit more flexibility in creating jars with different configurations. And even if not, it is a huge improvement in terms of readability of the build file and availability of documentation.

2024-04-09 16:48 UTC, simonpoole commented
Will give it a look ASAP.

2024-04-10 08:39 UTC, simonpoole commented
Changes look fine to me. I ran a build on my laptop, and outside of some of the tests failing (likely because of windows issues), that looked fine too.

2024-04-10 08:47 UTC, otbutz requested changes

2024-04-10 08:47 UTC, otbutz commented on pom.xml
> -                                    implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
That one is missing in the gradle version

2024-04-10 08:47 UTC, otbutz commented on pom.xml
> -                                <exclude>module-info.class</exclude>
Not sure if the gradle shadow plugin is doing it by default, but these excludes are otherwise missing.

2024-04-11 17:18 UTC, lonvia commented on pom.xml
> -                                <exclude>module-info.class</exclude>
Most of the are automatically included. The only one missing was `META-INF/versions/*/module-info.class`.

2024-04-11 17:18 UTC, lonvia commented on pom.xml
> -                                    implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
The only replacement I can find is a [very old plugin](https://plugins.gradle.org/plugin/io.paulbaker.shaded-log4j2-cachefile-transformer) that hasn't been touched since 2018. Any other suggestions for replacements?

2024-04-12 08:12 UTC, otbutz commented on pom.xml
> -                                    implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
The log4j2 support for Gradle seems to be lacking https://github.com/apache/logging-log4j-transform/issues/73

I think we can skip it as long as we don't have multiple log4j2 plugins. Otherwise we get problems with conflicting `Log4j2Plugins.dat` files.

2024-04-12 08:29 UTC, lonvia commented on pom.xml
> -                                    implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
OK, I'll leave it then. It seems to be compiling and running as is.

Thanks for looking and thanks for the review.

2024-04-12 09:41 UTC, merged

2024-05-02 09:44 UTC, lonvia commented on pom.xml
> -                                    implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
Note to self: found the proper way to solve this. Add

    transform(com.github.jengelman.gradle.plugins.shadow.transformers.Log4j2PluginsCacheFileTransformer)

to shadow step.

2025-01-23 03:34 UTC, Goooler commented on pom.xml
> -                                    implementation="org.apache.logging.log4j.maven.plugins.shade.transformer.Log4j2PluginCacheFileTransformer" />
`Log4j2PluginsCacheFileTransformer` may not work, I'm fixing it in https://github.com/GradleUp/shadow/pull/1175l.